apiVersion: apps/v1
kind: Deployment
metadata:
  name: da-bubble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: da-bubble
  template:
    metadata:
      labels:
        app: da-bubble
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: da-bubble
        image: ghcr.io/a-marbach/da-bubble:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: da-bubble-service
spec:
  type: NodePort
  selector:
    app: da-bubble
  ports:
    - protocol: TCP
      port: 80        # Port im Cluster
      targetPort: 80  # Port im Container
      nodePort: 30080 # Externer Port f√ºr Minikube