apiVersion: v1
kind: Service
metadata:
  name: da-bubble-service
spec:
  type: NodePort
  selector:
    app: da-bubble
  ports:
    - protocol: TCP
      port: 80        # Port im Cluster
      targetPort: 80  # Port im Container
      nodePort: 30080 # Port, auf dem Minikube zug√§nglich ist